CREATE TABLE borrow_records
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    borrow_date date                                    NOT NULL,
    due_date    date                                    NOT NULL,
    return_date date,
    status      VARCHAR(255),
    fine        DOUBLE PRECISION                        NOT NULL,
    book_id     BIGINT                                  NOT NULL,
    borrower_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_borrow_records PRIMARY KEY (id)
);

CREATE TABLE borrowers
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255),
    phone      VARCHAR(11)                             NOT NULL,
    address    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_borrowers PRIMARY KEY (id)
);

ALTER TABLE borrow_records
    ADD CONSTRAINT FK_BORROW_RECORDS_ON_BORROWER FOREIGN KEY (borrower_id) REFERENCES borrowers (id);